### ISSUE TITLE
error: No remote refs found for ‘flathub’

### ISSUE THREAD

**Issue by sschuberth** [mbugni/OneDriveGUIFlatpak#1]
When running

    flatpak-builder --user --verbose --install --install-deps-from=flathub --force-clean   build io.github.bpozdena.OneDriveGUI.yaml

on Fedora 38 (KDE spin) I'm getting

    error: No remote refs found for ‘flathub’

Sounds like a Git remote of a fixed name is assumed?

**Comment by mbugni** [comment]
Hi, did you execute this?

```shell
$ flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```

**Comment by sschuberth** [comment]
Ah, I did with `sudo` and without `--user`. So I guess I need to do the same here, too?

**Comment by mbugni** [comment]
From README:

> NOTE: if you want to install the app system wide, remove the --user option and the use sudo command.

So you can use `sudo` (for system wide usage) XOR `--user` (for local usage) option. See [documentation](https://docs.flatpak.org/en/latest/using-flatpak.html#system-versus-user).

**Comment by sschuberth** [comment]
Right, though for some reason I though this only applies to the first command, not the second one also. Anyway, it's clear now, thanks!
