### ISSUE TITLE
Submit to Flathub.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [mbugni/OneDriveGUIFlatpak#2]
https://github.com/bpozdena/OneDriveGUI/issues/22#issuecomment-1712458614 demonstrates how well it already operates.

**Comment by mbugni** [comment]
I'm not sure I understand this issue. Do you want me to publish the app?

This project is not for testing, but for helping. I'm not interested to be the app maintainer, because I don't use it.

**Comment by mbugni** [comment]
@RokeJulianLockhart do you want to be the maintainer of this app?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mbugni/OneDriveGUIFlatpak/issues/2#issuecomment-2509912096

@mbugni, I can't be - I'm not at the stage where I can maintain such a thing. My apologies.
